### ISSUE TITLE
Running rsdb.sh server returns /bin/bash^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by Friessn** [environmentalinformatics-marburg/rsdb-data#1]
When trying to run the rsdb server on a remote machine via ssh the abovementioned error was thrown. 
Apparently there are some DOS line endings in the bash script. 
Running dos2unix on rsdb.sh solved the problem for me.

**Comment by swoellauer** [comment]
Thanks for reporting this bug.
Line endings are corrected to unix style now.
