### ISSUE TITLE
Running RSDB server on Fedora 32

### ISSUE THREAD

**Issue by gbacaro** [environmentalinformatics-marburg/rsdb-data#2]
Hi! I'm trying to test the RSBD R package on my pc. 
I downloaded the rsdb-data-master folder, unzipped and use the chmod +x *.sh command in the console, but when trying to start the server, I got this problem

>bash ./server.sh

ERROR sever not started java.lang.NoClassDefFoundError: org/gdal/osr/SpatialReference    server.RunServer.main(RunServer.java:21)
INFO  server stopped                      server.RunServer.main(RunServer.java:31)

Thank you in advance
Giovanni

**Comment by swoellauer** [comment]
Can you confirm following the install instructions? "sudo apt install libgdal-java"
https://environmentalinformatics-marburg.github.io/rsdb/docs/server_installation/

This error reports that libgdal-java is not installed or not at an expected place or a not expected version. 

We only run and test RSDB on Ubuntu.
Can you modify the file "rsdb.sh" to test if following paths work for Fedora?

replace
`'rsdb.jar:/usr/share/java/gdal.jar:lib/*'`
by
`'rsdb.jar:/usr/lib/java/gdal/gdal.jar:lib/*'`
and
replace
`'/usr/lib/jni'`
by
`'/usr/lib/java/gdal'`

**Comment by gbacaro** [comment]
Great! It works perfectly on Fedora 32 after the suggested changes in the "rsdb.sh" file.
Just for your reference, and maybe for other Fedora users, this is my Java conf:

Java version
>java -version

openjdk version "1.8.0_272" 
OpenJDK Runtime Environment (build 1.8.0_272-b10) 
OpenJDK 64-Bit Server VM (build 25.272-b10, mixed mode)

>dnf install gdal-java
Package gdal-java-2.3.2-10.fc31.x86_64 is already installed.

**Comment by swoellauer** [comment]
Run compatibility for Linux Fedora is included in `rsdb.sh` now.
